version: "3.9"

services:
  make_up_db:
    container_name: make_up_db
    image: postgres:16.1
    restart: unless-stopped
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    expose:
      - ${DB_DOCKER_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  make_up_app:
    container_name: make_up_app
    depends_on:
      - make_up_db
    restart: on-failure
    image: make-up-app
    build: .
    ports:
      - ${SERVER_LOCAL_PORT}:${SERVER_DOCKER_PORT}
    expose:
      - ${SERVER_DOCKER_PORT}
    environment:
      - SERVER_PORT=${SERVER_LOCAL_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=make_up_db
      - DB_PORT=${DB_LOCAL_PORT}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - CRYPTO_SALT=${CRYPTO_SALT}
      - LOCAL_DOMAIN=${LOCAL_DOMAIN}
