version: "3.9"

services:
  db:
    image: postgres
    container_name: make_up_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=make_up"
      - "POSTGRES_PASSWORD=66vd52d"

  app:
    depends_on:
      - db
    restart: on-failure
    container_name: make_up
    image: make_up_app
    build: .
    ports:
      - "8080:8080"
    environment:
      db-url: jdbc:postgresql://db:5432/make_up
      db-username: postgres
      db-password: 66vd52d
